"""Universal Agent Runtime public facade.

The eager surface is the small SDK facade used by README and examples.
All legacy re-exports remain importable for compatibility through a lazy
module ``__getattr__``; prefer importing them from their submodules in new
code (see ``__dir__`` for the full compatibility names).

``_LEGACY_EXPORTS`` is a generated lookup table; E501 is exempted for this
file in pyproject so each mapping stays on one reviewable line.
"""

from __future__ import annotations

from typing import Any

from universal_agent.core import (
    Decision,
    DecisionType,
    ExecutionResult,
    ExecutionStatus,
    Goal,
    SuccessCriterion,
    Task,
    ToolDefinition,
    immutable_json,
)
from universal_agent.domain import RuntimeBuilder
from universal_agent.facade import (
    Agent,
    AgentConfigurationError,
)
from universal_agent.host import RuntimeHost
from universal_agent.model import ScriptedModelAdapter
from universal_agent.runtime import InMemoryEventSink
from universal_agent.service import RuntimeService
from universal_agent.state import (
    InMemoryStateStore,
    StateStore,
)
from universal_agent.tools import Tool

__all__ = [
    "Agent",
    "AgentConfigurationError",
    "Decision",
    "DecisionType",
    "ExecutionResult",
    "ExecutionStatus",
    "Goal",
    "InMemoryEventSink",
    "InMemoryStateStore",
    "RuntimeBuilder",
    "RuntimeHost",
    "RuntimeService",
    "ScriptedModelAdapter",
    "StateStore",
    "SuccessCriterion",
    "Task",
    "Tool",
    "ToolDefinition",
    "immutable_json",
]

# name -> "module.attribute" resolved lazily by __getattr__.
_LEGACY_EXPORTS: dict[str, str] = {
    "AGENT_TASK_API_VERSION": "universal_agent.multi_agent.AGENT_TASK_API_VERSION",
    "ActionReconcileContext": "universal_agent.domain.ActionReconcileContext",
    "ActionReconciler": "universal_agent.domain.ActionReconciler",
    "AgentActionProposal": "universal_agent.multi_agent.AgentActionProposal",
    "AgentConflictResolver": "universal_agent.multi_agent.AgentConflictResolver",
    "AgentDelegationBatchResult": "universal_agent.multi_agent.AgentDelegationBatchResult",
    "AgentDelegationBatchStatus": "universal_agent.multi_agent.AgentDelegationBatchStatus",
    "AgentDelegationDependencyError": "universal_agent.multi_agent.AgentDelegationDependencyError",
    "AgentDelegationError": "universal_agent.multi_agent.AgentDelegationError",
    "AgentDelegationLimitError": "universal_agent.multi_agent.AgentDelegationLimitError",
    "AgentDelegationSpec": "universal_agent.multi_agent.AgentDelegationSpec",
    "AgentDelegationState": "universal_agent.multi_agent.AgentDelegationState",
    "AgentDelegationTaskState": "universal_agent.multi_agent.AgentDelegationTaskState",
    "AgentExecutor": "universal_agent.multi_agent.AgentExecutor",
    "AgentExecutorNotRegisteredError": "universal_agent.multi_agent.AgentExecutorNotRegisteredError",
    "AgentExpectedOutput": "universal_agent.multi_agent.AgentExpectedOutput",
    "AgentId": "universal_agent.multi_agent.AgentId",
    "AgentInstanceNotRegisteredError": "universal_agent.multi_agent.AgentInstanceNotRegisteredError",
    "AgentInstanceRecord": "universal_agent.multi_agent.AgentInstanceRecord",
    "AgentInstanceStatus": "universal_agent.multi_agent.AgentInstanceStatus",
    "AgentOrchestrator": "universal_agent.multi_agent.AgentOrchestrator",
    "AgentProfile": "universal_agent.profile.AgentProfile",
    "AgentProfileNotRegisteredError": "universal_agent.multi_agent.AgentProfileNotRegisteredError",
    "AgentProfileRecord": "universal_agent.multi_agent.AgentProfileRecord",
    "AgentProposalId": "universal_agent.multi_agent.AgentProposalId",
    "AgentRegistry": "universal_agent.multi_agent.AgentRegistry",
    "AgentRegistryError": "universal_agent.multi_agent.AgentRegistryError",
    "AgentRegistrySnapshot": "universal_agent.multi_agent.AgentRegistrySnapshot",
    "AgentResultMerge": "universal_agent.multi_agent.AgentResultMerge",
    "AgentResultMergePolicy": "universal_agent.multi_agent.AgentResultMergePolicy",
    "AgentResultMergeStatus": "universal_agent.multi_agent.AgentResultMergeStatus",
    "AgentResultMerger": "universal_agent.multi_agent.AgentResultMerger",
    "AgentRuntime": "universal_agent.runtime.AgentRuntime",
    "AgentTaskConstraints": "universal_agent.multi_agent.AgentTaskConstraints",
    "AgentTaskId": "universal_agent.multi_agent.AgentTaskId",
    "AgentTaskRequest": "universal_agent.multi_agent.AgentTaskRequest",
    "AgentTaskResult": "universal_agent.multi_agent.AgentTaskResult",
    "AgentTaskResultStatus": "universal_agent.multi_agent.AgentTaskResultStatus",
    "AgentTaskUsage": "universal_agent.multi_agent.AgentTaskUsage",
    "AmbiguousDomainPackageError": "universal_agent.domain.AmbiguousDomainPackageError",
    "AmbiguousEcosystemRegistryItemError": "universal_agent.ecosystem.AmbiguousEcosystemRegistryItemError",
    "AmbiguousEvaluationDatasetError": "universal_agent.evaluation.dataset.AmbiguousEvaluationDatasetError",
    "AuditIntegrityReportView": "universal_agent.service.AuditIntegrityReportView",
    "AuditRecordView": "universal_agent.service.AuditRecordView",
    "BaseDomainRuntime": "universal_agent.domain.BaseDomainRuntime",
    "ConflictResolution": "universal_agent.multi_agent.ConflictResolution",
    "ConflictResolutionStatus": "universal_agent.multi_agent.ConflictResolutionStatus",
    "DeclarativeDomainRuntime": "universal_agent.domain.DeclarativeDomainRuntime",
    "DelegationEvent": "universal_agent.multi_agent.DelegationEvent",
    "DelegationEventId": "universal_agent.multi_agent.DelegationEventId",
    "DelegationLedger": "universal_agent.multi_agent.DelegationLedger",
    "DelegationManager": "universal_agent.multi_agent.DelegationManager",
    "DistributedCancellationResult": "universal_agent.distributed.DistributedCancellationResult",
    "DistributedCapacityGap": "universal_agent.distributed.DistributedCapacityGap",
    "DistributedExpiringLease": "universal_agent.distributed.DistributedExpiringLease",
    "DistributedHealthCheck": "universal_agent.distributed.DistributedHealthCheck",
    "DistributedHealthRecommendation": "universal_agent.distributed.DistributedHealthRecommendation",
    "DistributedHealthReport": "universal_agent.distributed.DistributedHealthReport",
    "DistributedHealthStatus": "universal_agent.distributed.DistributedHealthStatus",
    "DistributedLockConflictError": "universal_agent.distributed.DistributedLockConflictError",
    "DistributedLockLease": "universal_agent.distributed.DistributedLockLease",
    "DistributedLockLeaseId": "universal_agent.distributed.DistributedLockLeaseId",
    "DistributedLockLeaseLostError": "universal_agent.distributed.DistributedLockLeaseLostError",
    "DistributedLockLifecycleResult": "universal_agent.distributed.DistributedLockLifecycleResult",
    "DistributedLockOwnerId": "universal_agent.distributed.DistributedLockOwnerId",
    "DistributedLockSnapshot": "universal_agent.distributed.DistributedLockSnapshot",
    "DistributedMaintenanceResult": "universal_agent.distributed.DistributedMaintenanceResult",
    "DistributedPendingActionSchedulingResult": "universal_agent.service.DistributedPendingActionSchedulingResult",
    "DistributedPruneResult": "universal_agent.distributed.DistributedPruneResult",
    "DistributedRuntimeCoordinator": "universal_agent.distributed.DistributedRuntimeCoordinator",
    "DistributedRuntimeSnapshot": "universal_agent.distributed.DistributedRuntimeSnapshot",
    "DistributedSchedulingResult": "universal_agent.distributed.DistributedSchedulingResult",
    "DistributedWorkerLifecycleResult": "universal_agent.distributed.DistributedWorkerLifecycleResult",
    "DoctorReportView": "universal_agent.service.DoctorReportView",
    "DomainConfig": "universal_agent.host.DomainConfig",
    "DomainLoader": "universal_agent.domain.DomainLoader",
    "DomainPackage": "universal_agent.domain.DomainPackage",
    "DomainPackageCheck": "universal_agent.domain.DomainPackageCheck",
    "DomainPackageCompatibility": "universal_agent.domain.DomainPackageCompatibility",
    "DomainPackageManifest": "universal_agent.domain.DomainPackageManifest",
    "DomainPackageNotFoundError": "universal_agent.domain.DomainPackageNotFoundError",
    "DomainPackageRegistry": "universal_agent.domain.DomainPackageRegistry",
    "DomainPackageRuntimeActivation": "universal_agent.domain.DomainPackageRuntimeActivation",
    "DomainPackageRuntimeLoadError": "universal_agent.domain.DomainPackageRuntimeLoadError",
    "DomainPackageScaffoldResult": "universal_agent.domain.DomainPackageScaffoldResult",
    "DomainPackageScaffoldSpec": "universal_agent.domain.DomainPackageScaffoldSpec",
    "DomainPackageValidationError": "universal_agent.domain.DomainPackageValidationError",
    "DomainPackageVerificationReport": "universal_agent.domain.DomainPackageVerificationReport",
    "DomainPackageView": "universal_agent.service.DomainPackageView",
    "DomainRuntimeLoadContext": "universal_agent.domain.DomainRuntimeLoadContext",
    "DomainRuntimeSpec": "universal_agent.domain.DomainRuntimeSpec",
    "DomainValidationError": "universal_agent.domain.DomainValidationError",
    "EcosystemCatalog": "universal_agent.ecosystem.EcosystemCatalog",
    "EcosystemCatalogCheck": "universal_agent.ecosystem.EcosystemCatalogCheck",
    "EcosystemCatalogSummary": "universal_agent.ecosystem.EcosystemCatalogSummary",
    "EcosystemCatalogVerificationReport": "universal_agent.ecosystem.EcosystemCatalogVerificationReport",
    "EcosystemDomainPackageInstallCandidate": "universal_agent.ecosystem.EcosystemDomainPackageInstallCandidate",
    "EcosystemDomainPackageInstallPlan": "universal_agent.ecosystem.EcosystemDomainPackageInstallPlan",
    "EcosystemDomainPackageInstallResult": "universal_agent.ecosystem.EcosystemDomainPackageInstallResult",
    "EcosystemDomainPackageRef": "universal_agent.ecosystem.EcosystemDomainPackageRef",
    "EcosystemEvaluationDatasetInstallCandidate": "universal_agent.ecosystem.EcosystemEvaluationDatasetInstallCandidate",
    "EcosystemEvaluationDatasetRef": "universal_agent.ecosystem.EcosystemEvaluationDatasetRef",
    "EcosystemEvaluationDatasetSuiteRef": "universal_agent.ecosystem.EcosystemEvaluationDatasetSuiteRef",
    "EcosystemInstallPlan": "universal_agent.ecosystem.EcosystemInstallPlan",
    "EcosystemInstallResult": "universal_agent.ecosystem.EcosystemInstallResult",
    "EcosystemProfileInstallCandidate": "universal_agent.ecosystem.EcosystemProfileInstallCandidate",
    "EcosystemProfileRef": "universal_agent.ecosystem.EcosystemProfileRef",
    "EcosystemRegistryIndex": "universal_agent.ecosystem.EcosystemRegistryIndex",
    "EcosystemRegistryInstallError": "universal_agent.ecosystem.EcosystemRegistryInstallError",
    "EcosystemRegistryItemNotFoundError": "universal_agent.ecosystem.EcosystemRegistryItemNotFoundError",
    "EcosystemRegistryManifest": "universal_agent.ecosystem.EcosystemRegistryManifest",
    "EcosystemRegistryNotFoundError": "universal_agent.ecosystem.EcosystemRegistryNotFoundError",
    "EcosystemRegistrySignatureVerification": "universal_agent.ecosystem.EcosystemRegistrySignatureVerification",
    "EcosystemRegistrySignatureVerifier": "universal_agent.ecosystem.EcosystemRegistrySignatureVerifier",
    "EcosystemRegistryStoreNotFoundError": "universal_agent.ecosystem.EcosystemRegistryStoreNotFoundError",
    "EcosystemRegistryTrustPolicy": "universal_agent.ecosystem.EcosystemRegistryTrustPolicy",
    "EcosystemRegistryValidationError": "universal_agent.ecosystem.EcosystemRegistryValidationError",
    "EcosystemRegistryWriteResult": "universal_agent.ecosystem.EcosystemRegistryWriteResult",
    "EnvSecretProvider": "universal_agent.security.EnvSecretProvider",
    "EvaluationDataset": "universal_agent.evaluation.dataset.EvaluationDataset",
    "EvaluationDatasetCheck": "universal_agent.evaluation.dataset.EvaluationDatasetCheck",
    "EvaluationDatasetIdentity": "universal_agent.evaluation.dataset.EvaluationDatasetIdentity",
    "EvaluationDatasetManifest": "universal_agent.evaluation.dataset.EvaluationDatasetManifest",
    "EvaluationDatasetNotFoundError": "universal_agent.evaluation.dataset.EvaluationDatasetNotFoundError",
    "EvaluationDatasetRegistry": "universal_agent.evaluation.dataset.EvaluationDatasetRegistry",
    "EvaluationDatasetSuiteRef": "universal_agent.evaluation.dataset.EvaluationDatasetSuiteRef",
    "EvaluationDatasetValidationError": "universal_agent.evaluation.dataset.EvaluationDatasetValidationError",
    "EvaluationDatasetVerificationReport": "universal_agent.evaluation.dataset.EvaluationDatasetVerificationReport",
    "EventCursorError": "universal_agent.runtime.EventCursorError",
    "EvidenceView": "universal_agent.runtime.EvidenceView",
    "FakeModel": "universal_agent.model.FakeModel",
    "FileDelegationLedger": "universal_agent.multi_agent.FileDelegationLedger",
    "FileDistributedLockRegistry": "universal_agent.distributed.FileDistributedLockRegistry",
    "FileEcosystemRegistryStore": "universal_agent.ecosystem.FileEcosystemRegistryStore",
    "FileEventStore": "universal_agent.persistence.FileEventStore",
    "FileRuntimeStore": "universal_agent.persistence.FileRuntimeStore",
    "FileSecretProvider": "universal_agent.security.FileSecretProvider",
    "FileSessionStore": "universal_agent.persistence.FileSessionStore",
    "FileWorkQueue": "universal_agent.distributed.FileWorkQueue",
    "FileWorkerRegistry": "universal_agent.distributed.FileWorkerRegistry",
    "HttpxJsonHttpTransport": "universal_agent.model.HttpxJsonHttpTransport",
    "HttpxPrometheusTransport": "universal_agent.domains.observability.HttpxPrometheusTransport",
    "InMemoryDelegationLedger": "universal_agent.multi_agent.InMemoryDelegationLedger",
    "InMemoryDistributedLockRegistry": "universal_agent.distributed.InMemoryDistributedLockRegistry",
    "InMemoryWorkQueue": "universal_agent.distributed.InMemoryWorkQueue",
    "InMemoryWorkerRegistry": "universal_agent.distributed.InMemoryWorkerRegistry",
    "JsonHttpModelAdapter": "universal_agent.model.JsonHttpModelAdapter",
    "JsonHttpModelError": "universal_agent.model.JsonHttpModelError",
    "JsonHttpModelTransport": "universal_agent.model.JsonHttpModelTransport",
    "LeaseId": "universal_agent.distributed.LeaseId",
    "LeaseLostError": "universal_agent.distributed.LeaseLostError",
    "MetricsBackend": "universal_agent.domains.observability.MetricsBackend",
    "MetricsHealthEvaluator": "universal_agent.domains.observability.MetricsHealthEvaluator",
    "ModelAdapter": "universal_agent.model.ModelAdapter",
    "ModelConfig": "universal_agent.host.ModelConfig",
    "ModelProvider": "universal_agent.host.ModelProvider",
    "ModelUsage": "universal_agent.model.ModelUsage",
    "ModelUsageProvider": "universal_agent.model.ModelUsageProvider",
    "MultiAgentEvaluationCheck": "universal_agent.multi_agent.MultiAgentEvaluationCheck",
    "MultiAgentEvaluationExpectations": "universal_agent.multi_agent.MultiAgentEvaluationExpectations",
    "MultiAgentEvaluationReport": "universal_agent.multi_agent.MultiAgentEvaluationReport",
    "MultiAgentMergeEvaluator": "universal_agent.multi_agent.MultiAgentMergeEvaluator",
    "NoEligibleAgentError": "universal_agent.multi_agent.NoEligibleAgentError",
    "NoWorkAvailable": "universal_agent.distributed.NoWorkAvailable",
    "ObservabilityDomain": "universal_agent.domains.observability.ObservabilityDomain",
    "ObservabilityEvidenceExtractor": "universal_agent.domains.observability.ObservabilityEvidenceExtractor",
    "ObservabilityQueryMetricsTool": "universal_agent.domains.observability.ObservabilityQueryMetricsTool",
    "OpenAIChatCompletionsModelAdapter": "universal_agent.model.OpenAIChatCompletionsModelAdapter",
    "OpenAIModelTransport": "universal_agent.model.OpenAIModelTransport",
    "OpenAIResponsesModelAdapter": "universal_agent.model.OpenAIResponsesModelAdapter",
    "OpenAISdkModelTransport": "universal_agent.model.OpenAISdkModelTransport",
    "ProfileCatalog": "universal_agent.profile.ProfileCatalog",
    "ProfileCatalogCheck": "universal_agent.profile.ProfileCatalogCheck",
    "ProfileCatalogEntry": "universal_agent.profile.ProfileCatalogEntry",
    "ProfileCatalogVerificationReport": "universal_agent.profile.ProfileCatalogVerificationReport",
    "ProfileConfig": "universal_agent.profile.ProfileConfig",
    "ProfileConfigNotFoundError": "universal_agent.profile.ProfileConfigNotFoundError",
    "ProfileRegistry": "universal_agent.profile.ProfileRegistry",
    "PrometheusBackend": "universal_agent.domains.observability.PrometheusBackend",
    "PrometheusQueryError": "universal_agent.domains.observability.PrometheusQueryError",
    "PrometheusTransport": "universal_agent.domains.observability.PrometheusTransport",
    "RuntimeAPI": "universal_agent.runtime.RuntimeAPI",
    "RuntimeAgentExecutor": "universal_agent.multi_agent.RuntimeAgentExecutor",
    "RuntimeConfig": "universal_agent.host.RuntimeConfig",
    "RuntimeConfigDomainView": "universal_agent.service.RuntimeConfigDomainView",
    "RuntimeConfigView": "universal_agent.service.RuntimeConfigView",
    "RuntimeCostView": "universal_agent.service.RuntimeCostView",
    "RuntimeEventBatch": "universal_agent.runtime.RuntimeEventBatch",
    "RuntimeEventRepairUnavailableError": "universal_agent.runtime.RuntimeEventRepairUnavailableError",
    "RuntimeLimitsConfig": "universal_agent.host.RuntimeLimitsConfig",
    "RuntimeLogRecordView": "universal_agent.service.RuntimeLogRecordView",
    "RuntimeMetricsView": "universal_agent.service.RuntimeMetricsView",
    "RuntimeSDKError": "universal_agent.service.sdk.RuntimeSDKError",
    "RuntimeSecretRefView": "universal_agent.service.RuntimeSecretRefView",
    "RuntimeSessionBatch": "universal_agent.runtime.RuntimeSessionBatch",
    "RuntimeTraceSpanView": "universal_agent.service.RuntimeTraceSpanView",
    "SDKGoal": "universal_agent.service.sdk.SDKGoal",
    "SDKRunResult": "universal_agent.service.sdk.SDKRunResult",
    "SDKSuccessCriterion": "universal_agent.service.sdk.SDKSuccessCriterion",
    "SDKTask": "universal_agent.service.sdk.SDKTask",
    "SQLiteDistributedLockRegistry": "universal_agent.distributed.SQLiteDistributedLockRegistry",
    "SQLiteEventStore": "universal_agent.persistence.SQLiteEventStore",
    "SQLiteOutboxEvent": "universal_agent.persistence.SQLiteOutboxEvent",
    "SQLiteRuntimeStore": "universal_agent.persistence.SQLiteRuntimeStore",
    "SQLiteSessionStore": "universal_agent.persistence.SQLiteSessionStore",
    "SQLiteWorkQueue": "universal_agent.distributed.SQLiteWorkQueue",
    "SQLiteWorkerRegistry": "universal_agent.distributed.SQLiteWorkerRegistry",
    "SecretProvider": "universal_agent.security.SecretProvider",
    "SecretRef": "universal_agent.host.SecretRef",
    "SecretReference": "universal_agent.security.SecretReference",
    "SecretResolution": "universal_agent.security.SecretResolution",
    "SecretResolutionReport": "universal_agent.security.SecretResolutionReport",
    "SecretResolutionStatus": "universal_agent.security.SecretResolutionStatus",
    "SecretSource": "universal_agent.host.SecretSource",
    "SessionDiagnosticsView": "universal_agent.runtime.SessionDiagnosticsView",
    "SessionExplorerView": "universal_agent.service.SessionExplorerView",
    "SessionSummaryView": "universal_agent.runtime.SessionSummaryView",
    "SessionWorldView": "universal_agent.service.SessionWorldView",
    "StateEventCommitView": "universal_agent.runtime.StateEventCommitView",
    "StateEventRepairReport": "universal_agent.service.StateEventRepairReport",
    "StateEventRepairSkipView": "universal_agent.service.StateEventRepairSkipView",
    "StateEventRepairView": "universal_agent.service.StateEventRepairView",
    "StaticMetricsBackend": "universal_agent.domains.observability.StaticMetricsBackend",
    "StdlibJsonHttpTransport": "universal_agent.model.StdlibJsonHttpTransport",
    "StoreBackend": "universal_agent.host.StoreBackend",
    "StoreConfig": "universal_agent.host.StoreConfig",
    "UniversalAgentRuntime": "universal_agent.service.sdk.UniversalAgentRuntime",
    "WorkHandler": "universal_agent.distributed.WorkHandler",
    "WorkHandlerResult": "universal_agent.distributed.WorkHandlerResult",
    "WorkHandlerStatus": "universal_agent.distributed.WorkHandlerStatus",
    "WorkItem": "universal_agent.distributed.WorkItem",
    "WorkItemId": "universal_agent.distributed.WorkItemId",
    "WorkItemNotFoundError": "universal_agent.distributed.WorkItemNotFoundError",
    "WorkItemSnapshot": "universal_agent.distributed.WorkItemSnapshot",
    "WorkItemStatus": "universal_agent.distributed.WorkItemStatus",
    "WorkKind": "universal_agent.distributed.WorkKind",
    "WorkQueueSnapshot": "universal_agent.distributed.WorkQueueSnapshot",
    "WorkQueueWorker": "universal_agent.distributed.WorkQueueWorker",
    "WorkScheduler": "universal_agent.distributed.WorkScheduler",
    "WorkerId": "universal_agent.distributed.WorkerId",
    "WorkerLease": "universal_agent.distributed.WorkerLease",
    "WorkerNotFoundError": "universal_agent.distributed.WorkerNotFoundError",
    "WorkerRecord": "universal_agent.distributed.WorkerRecord",
    "WorkerRegistrySnapshot": "universal_agent.distributed.WorkerRegistrySnapshot",
    "WorkerRunResult": "universal_agent.distributed.WorkerRunResult",
    "WorkerRunStatus": "universal_agent.distributed.WorkerRunStatus",
    "WorkerSnapshot": "universal_agent.distributed.WorkerSnapshot",
    "WorkerStatus": "universal_agent.distributed.WorkerStatus",
    "WorldEntityView": "universal_agent.service.WorldEntityView",
    "WorldFactEvidenceView": "universal_agent.service.WorldFactEvidenceView",
    "WorldFactHistoryView": "universal_agent.service.WorldFactHistoryView",
    "WorldFactView": "universal_agent.service.WorldFactView",
    "WorldNeighborhoodView": "universal_agent.service.WorldNeighborhoodView",
    "WorldRelationView": "universal_agent.service.WorldRelationView",
    "agent_delegation_batch_result_payload": "universal_agent.multi_agent.agent_delegation_batch_result_payload",
    "agent_delegation_spec_payload": "universal_agent.multi_agent.agent_delegation_spec_payload",
    "agent_delegation_state_payload": "universal_agent.multi_agent.agent_delegation_state_payload",
    "agent_instance_record_payload": "universal_agent.multi_agent.agent_instance_record_payload",
    "agent_profile_record_payload": "universal_agent.multi_agent.agent_profile_record_payload",
    "agent_registry_from_snapshot": "universal_agent.multi_agent.agent_registry_from_snapshot",
    "agent_registry_snapshot_payload": "universal_agent.multi_agent.agent_registry_snapshot_payload",
    "agent_result_merge_payload": "universal_agent.multi_agent.agent_result_merge_payload",
    "agent_task_request_payload": "universal_agent.multi_agent.agent_task_request_payload",
    "agent_task_result_payload": "universal_agent.multi_agent.agent_task_result_payload",
    "build_configured_model_adapter": "universal_agent.host.build_configured_model_adapter",
    "build_distributed_health_report": "universal_agent.distributed.build_distributed_health_report",
    "build_distributed_runtime_snapshot": "universal_agent.distributed.build_distributed_runtime_snapshot",
    "build_domain_package_manifest": "universal_agent.domain.build_domain_package_manifest",
    "build_domain_runtime": "universal_agent.domain.build_domain_runtime",
    "build_ecosystem_registry_manifest": "universal_agent.ecosystem.build_ecosystem_registry_manifest",
    "conflict_resolution_payload": "universal_agent.multi_agent.conflict_resolution_payload",
    "decode_agent_delegation_batch_result": "universal_agent.multi_agent.decode_agent_delegation_batch_result",
    "decode_agent_delegation_spec": "universal_agent.multi_agent.decode_agent_delegation_spec",
    "decode_agent_delegation_state": "universal_agent.multi_agent.decode_agent_delegation_state",
    "decode_agent_instance_record": "universal_agent.multi_agent.decode_agent_instance_record",
    "decode_agent_profile_record": "universal_agent.multi_agent.decode_agent_profile_record",
    "decode_agent_registry_snapshot": "universal_agent.multi_agent.decode_agent_registry_snapshot",
    "decode_agent_result_merge": "universal_agent.multi_agent.decode_agent_result_merge",
    "decode_agent_task_request": "universal_agent.multi_agent.decode_agent_task_request",
    "decode_agent_task_result": "universal_agent.multi_agent.decode_agent_task_result",
    "decode_conflict_resolution": "universal_agent.multi_agent.decode_conflict_resolution",
    "decode_delegation_event": "universal_agent.multi_agent.decode_delegation_event",
    "decode_domain_package_manifest": "universal_agent.domain.decode_domain_package_manifest",
    "decode_ecosystem_registry_manifest": "universal_agent.ecosystem.decode_ecosystem_registry_manifest",
    "decode_evaluation_dataset_manifest": "universal_agent.evaluation.dataset.decode_evaluation_dataset_manifest",
    "decode_multi_agent_evaluation_expectations": "universal_agent.multi_agent.decode_multi_agent_evaluation_expectations",
    "decode_multi_agent_evaluation_report": "universal_agent.multi_agent.decode_multi_agent_evaluation_report",
    "delegation_event_payload": "universal_agent.multi_agent.delegation_event_payload",
    "domain_package_scaffold_spec_from_runtime_spec": "universal_agent.domain.domain_package_scaffold_spec_from_runtime_spec",
    "encode_domain_package_manifest": "universal_agent.domain.encode_domain_package_manifest",
    "encode_ecosystem_registry_manifest": "universal_agent.ecosystem.encode_ecosystem_registry_manifest",
    "encode_evaluation_dataset_manifest": "universal_agent.evaluation.dataset.encode_evaluation_dataset_manifest",
    "install_ecosystem": "universal_agent.ecosystem.install_ecosystem",
    "install_ecosystem_domain_packages": "universal_agent.ecosystem.install_ecosystem_domain_packages",
    "load_domain_package": "universal_agent.domain.load_domain_package",
    "load_domain_package_runtime": "universal_agent.domain.load_domain_package_runtime",
    "load_ecosystem_catalog": "universal_agent.ecosystem.load_ecosystem_catalog",
    "load_ecosystem_registry_index": "universal_agent.ecosystem.load_ecosystem_registry_index",
    "load_ecosystem_registry_manifest": "universal_agent.ecosystem.load_ecosystem_registry_manifest",
    "load_evaluation_dataset": "universal_agent.evaluation.dataset.load_evaluation_dataset",
    "load_profile_catalog": "universal_agent.profile.load_profile_catalog",
    "multi_agent_evaluation_expectations_payload": "universal_agent.multi_agent.multi_agent_evaluation_expectations_payload",
    "multi_agent_evaluation_report_payload": "universal_agent.multi_agent.multi_agent_evaluation_report_payload",
    "plan_ecosystem_domain_package_install": "universal_agent.ecosystem.plan_ecosystem_domain_package_install",
    "plan_ecosystem_install": "universal_agent.ecosystem.plan_ecosystem_install",
    "redact_sensitive_mapping": "universal_agent.security.redact_sensitive_mapping",
    "redact_sensitive_value": "universal_agent.security.redact_sensitive_value",
    "rejected_agent_task_result": "universal_agent.multi_agent.rejected_agent_task_result",
    "resolve_secret_refs": "universal_agent.security.resolve_secret_refs",
    "resolve_secret_value": "universal_agent.security.resolve_secret_value",
    "scaffold_domain_package": "universal_agent.domain.scaffold_domain_package",
    "verify_domain_package": "universal_agent.domain.verify_domain_package",
    "verify_domain_package_registry": "universal_agent.domain.verify_domain_package_registry",
    "verify_evaluation_dataset": "universal_agent.evaluation.dataset.verify_evaluation_dataset",
    "verify_evaluation_dataset_registry": "universal_agent.evaluation.dataset.verify_evaluation_dataset_registry",
    "verify_profile_catalog": "universal_agent.profile.verify_profile_catalog",
    "verify_profile_catalog_entry": "universal_agent.profile.verify_profile_catalog_entry",
    "write_ecosystem_registry_manifest": "universal_agent.ecosystem.write_ecosystem_registry_manifest",
}


def __getattr__(name: str) -> Any:
    path = _LEGACY_EXPORTS.get(name)
    if path is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    # Compatibility plan: lazy re-export of the pre-facade root API.
    import importlib

    module_path, _, attribute = path.rpartition(".")
    value = getattr(importlib.import_module(module_path), attribute)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(_LEGACY_EXPORTS))
